title: Adriana Delgado
logo: assets/img/cv.jpeg
description: Perfil
show_downloads: true
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
gem "github-pages", group: :jekyll_plugins
