title: Adriana Delgado Nalvarte
description: Portfolio 
logo: assets/img/cv.jpeg

show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
gem "github-pages", group: :jekyll_plugins
